<?php
 echo'error_reporting(0);'.PHP_EOL;
 echo'use app\tatiye;'.PHP_EOL;
 echo'use app\tatiyeNetAuthorization AS Authorization;'.PHP_EOL;
 echo'use app\Graph\Response;'.PHP_EOL;
 echo '$NEWTOKEN="'.$NEWTOKEN.'";'.PHP_EOL;
 echo'  Authorization::init(1);'.PHP_EOL;
 echo'  $Text=tatiye::Text();'.PHP_EOL;
 echo'  $tabel=$_POST["tabel"];'.PHP_EOL;
 echo'  $id   =$_POST["id"];'.PHP_EOL;
 echo'  $db   =new tatiye();'.PHP_EOL;
 echo'if($_SERVER["REQUEST_METHOD"] === "POST") {'.PHP_EOL;
 echo'$row= tatiye::fetch($tabel,"*","id=$id");'.PHP_EOL;
 echo'// DIREKTORY FILE'.PHP_EOL;
 echo'if (!file_exists(tatiye::dir()."/public/drive/".tatiye::dt("Y")."/".tatiye::dt("M")."/".$id)) {'.PHP_EOL;
 echo'  @mkdir(tatiye::dir()."/public/drive/".tatiye::dt("Y"), 0700);'.PHP_EOL;
 echo'  @mkdir(tatiye::dir()."/public/drive/".tatiye::dt("Y")."/".tatiye::dt("M"), 0700);'.PHP_EOL;
 echo'  @mkdir(tatiye::dir()."/public/drive/".tatiye::dt("Y")."/".tatiye::dt("M")."/".$id, 0700);'.PHP_EOL;
 echo'}'.PHP_EOL;
 echo'$target_dir = tatiye::dir()."/public/drive/".tatiye::dt("Y")."/".tatiye::dt("M")."/".$id."/";'.PHP_EOL;
 echo'$dir_file = tatiye::dt("Y")."/".tatiye::dt("M")."/".$id."/";'.PHP_EOL;
 echo'$uploadOk = 1;'.PHP_EOL;
 echo'    $file      = basename($_FILES["filename"]["name"]);'.PHP_EOL; 
 echo'    $fileType  = pathinfo($file, PATHINFO_EXTENSION); '.PHP_EOL;
 echo'    $fileName  = $Text->strreplace([$file," ","_"]); '.PHP_EOL;
 echo'    $target_file =  $target_dir . $fileName;'.PHP_EOL;
 echo'    $dir_fileName = $dir_file.$fileName;'.PHP_EOL;
 echo'$filenameType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));'.PHP_EOL;
 echo'// Check if image file is a actual image or fake image'.PHP_EOL;
 echo'if(isset($_POST["submit"])) {'.PHP_EOL;
 echo'  $check = getimagesize($_FILES["filename"]["tmp_name"]);'.PHP_EOL;
 echo'  if($check !== false) {'.PHP_EOL;
 echo'    $val["status"]= "File adalah gambar - " . $check["mime"] . ".";'.PHP_EOL;
 echo'    $uploadOk = 1;'.PHP_EOL;
 echo'  } else {'.PHP_EOL;
 echo'    $val["status"]= "File bukan gambar.";'.PHP_EOL;
 echo'    $uploadOk = 0;'.PHP_EOL;
 echo'  }'.PHP_EOL;
 echo'}'.PHP_EOL;
 echo'// Check if file already exists'.PHP_EOL;
 echo'if (file_exists($target_file)) {'.PHP_EOL;
 echo'  $val["status"]= "Maaf, file sudah ada";'.PHP_EOL;
 echo'  $uploadOk = 0;'.PHP_EOL;
 echo'}'.PHP_EOL;
 echo'// Check file size'.PHP_EOL;
 echo'if ($_FILES["filename"]["size"] > 500000) {'.PHP_EOL;
 echo'  $val["status"]= "Maaf, file Anda terlalu besar.";'.PHP_EOL;
 echo'  $uploadOk = 0;'.PHP_EOL;
 echo'}'.PHP_EOL;
echo'// Allow certain file formats'.PHP_EOL;
echo'if($filenameType != "docx" && $filenameType != "xlsx" && $filenameType != "pdf"'.PHP_EOL; 
echo'&& $filenameType != "pptx" ) {'.PHP_EOL;
echo'  $val["status"]= "Maaf, hanya file doxc, xlsx, pdf & pptx yang diperbolehkan.";'.PHP_EOL;
echo'  $uploadOk = 0;'.PHP_EOL;
echo'}'.PHP_EOL;
 echo'// Check if $uploadOk is set to 0 by an errortype'.PHP_EOL;
 echo'if ($uploadOk == 0) {'.PHP_EOL;
 echo'  $val["status"]= "Maaf, file Anda tidak diunggah.";'.PHP_EOL;
 echo'// if everything is ok, try to upload file'.PHP_EOL;
 echo'} else {'.PHP_EOL;
 echo'  if (move_uploaded_file($_FILES["filename"]["tmp_name"], $target_file)) {'.PHP_EOL;
 echo'    $val["status"]= "File  ". htmlspecialchars( basename( $_FILES["filename"]["name"])). " telah diunggah..";'.PHP_EOL;
 echo'      $Exp=array('.PHP_EOL;
 echo'             "userid"   =>$_POST["userid"],'.PHP_EOL;
 echo'             "keyid"    =>$id,'.PHP_EOL;
 echo'             "nmtabel"  =>$tabel,'.PHP_EOL;
 echo'             "filename" =>$dir_fileName,'.PHP_EOL;
 echo'             "time"     =>tatiye::tm(),'.PHP_EOL;                                               
 echo'             "categori" =>"images",'.PHP_EOL;                                               
 echo'             "fileType" =>$filenameType,'.PHP_EOL;                                               
 echo'             "date"     =>tatiye::dt("EN"),'.PHP_EOL;                                           
 echo'             "bulan"    =>tatiye::dt("M"),'.PHP_EOL;                                            
 echo'             "tahun"    =>tatiye::dt("Y"),'.PHP_EOL; 
 echo'         );'.PHP_EOL;
 echo'         $result=$db->que($Exp)->insert("appfile");'.PHP_EOL;
 echo'  } else {'.PHP_EOL;
 echo'    $val["status"]= "Maaf, terjadi kesalahan saat mengunggah file Anda.";'.PHP_EOL;
 echo'  }'.PHP_EOL;
 echo'}'.PHP_EOL;
 echo'        http_response_code(200);'.PHP_EOL;
 echo'        echo json_encode($val);'.PHP_EOL;
 echo'} else {'.PHP_EOL;
 echo'      return tatiye::index();'.PHP_EOL;
 echo'}'.PHP_EOL;


