<?php 
 use app\tatiye;
 $row=tatiye::BQ($APPQUERY);
 echo 'error_reporting(0);'.PHP_EOL;
 echo 'use app\tatiye;'.PHP_EOL;
 echo 'use app\models\storage;'.PHP_EOL;
 echo '$NEWTOKEN="'.$NEWTOKEN.'";'.PHP_EOL;
 echo 'if($_SERVER["REQUEST_METHOD"] === "POST") {'.PHP_EOL;
 echo '$val=json_decode(file_get_contents("php://input"));'.PHP_EOL;
 echo '$db=new tatiye();'.PHP_EOL;
 echo '$tabel="'.$tabel.'";'.PHP_EOL;
 echo '$keywords="'.$keywords.'";'.PHP_EOL;
 echo '$COUNT=tatiye::fetch("'.$tabel.'"," COUNT(*) as count");'.PHP_EOL;
 echo '$arry["update"]=tatiye::dt("DTIE");'.PHP_EOL;
 echo '$arry["total"] =$COUNT["count"];'.PHP_EOL;
 echo '$arry["data"]=array();'.PHP_EOL;
 echo '$QUERY="SELECT '.PHP_EOL;
 echo '        id AS uid, '.$keywords.''.PHP_EOL;
 echo '        FROM '.$tabel.''.PHP_EOL;
 echo '        ORDER BY id DESC";'.PHP_EOL;
 echo '$result=$db->query($QUERY);'.PHP_EOL;
 echo ' while($row=$result->fetch_assoc()){'.PHP_EOL;
 echo '    array_push($arry["data"],$row);'.PHP_EOL;
 echo '}'.PHP_EOL;
 echo ' http_response_code(200);'.PHP_EOL;
 echo '    echo json_encode($arry); '.PHP_EOL;
echo '} else {'.PHP_EOL;
echo '  return tatiye::index();'.PHP_EOL;
echo '}'.PHP_EOL;