<?php
  error_reporting(0);                                                                                                  
  $routeLink=[                                                                                                         
   "ecosystem"    =>[                                                                                                  
     "Download"  =>["Github@ngorei ","picons-106","docs/intro/Download"],                                              
     "Installation"  =>["NPM tatiye","picons-193","docs/intro/Installation"],                                          
     "Configurasi"  =>["Package &amp; Database","picons-194","docs/intro/Configurasi"],                                
     "License key"  =>["Trial 25-day","picons-114","docs/intro/License"],                                              
     "Links &amp; Pages"  =>["Package &amp; Database","picons-359","docs/intro/Router"],                               
     "API Reference"  =>["Package &amp; Database","picons-359","docs/ApiReference"],                                   
   ],                                                                                                                  
   "core"    =>[                                                                                                       
     "Website"  =>["Public theme","picons-496","docs/core/Website"],                                                   
     "Mobile"  =>["Detecting Browser","picons-324","docs/core/Mobile"],                                                
     "OS, Android"  =>["Webview &amp; Native ","picons-116","docs/core/App"],                                          
     "Dashboard"  =>["Management Package","picons-309","docs/core/Dashboard"],                                         
   ],                                                                                                                  
   "core_web"    =>[                                                                                                   
     "Links &amp; Pages"  =>["Public theme","picons-496","docs/core/Website#ngorei=Links-Pages"],                      
     "Scroll Content"  =>["Public theme","picons-496","docs/core/Website#content=Scroll-Content"],                     
     "Icon Images"  =>["Detecting Browser","picons-324","docs/core/Website#ngorei=Icon-Images"],                       
     "Height"  =>["Public theme","picons-496","docs/core/Website#ngorei=Height"],                                      
     "Width"  =>["Detecting Browser","picons-324","docs/core/Website#ngorei=Width"],                                   
     "Size"  =>["Detecting Browser","picons-324","docs/core/Website#ngorei=Size"],                                     
     "Font Size"  =>["Detecting Browser","picons-324","docs/core/Website#ngorei=Font-Size"],                           
     "Margin"  =>["Detecting Browser","picons-324","docs/core/Website#ngorei=Margin"],                                 
     "Padding"  =>["Webview &amp; Native ","picons-116","docs/core/Website#ngorei=Padding"],                           
     "Background"  =>["Webview &amp; Native ","picons-116","docs/core/Website#ngorei=Background"],                     
     "Color Text"  =>["Webview &amp; Native ","picons-116","docs/core/Website#ngorei=Color-Text"],                     
     "Image Resizer"  =>["Webview &amp; Native ","picons-116","docs/core/Website#images=Image-Resizer"],               
     "Resize Width"  =>["Webview &amp; Native ","padding-left:20px","docs/core/Website#images=Image-Resize-Width"],    
     "Resize Height"  =>["Webview &amp; Native ","padding-left:20px","docs/core/Website#images=Image-Resize-Height"],  
     "Watermark"  =>["Webview &amp; Native ","padding-left:20px","docs/core/Website#images=Image-Watermark"],          
     "Crop Image"  =>["Webview &amp; Native ","padding-left:20px","docs/core/Website#images=Crop-Image"],              
     "Black White"  =>["Webview &amp; Native ","padding-left:20px","docs/core/Website#images=Images-Black-White"],     
   ],                                                                                                                  
   "framework"    =>[                                                                                                  
     "HTML"  =>["Ngorei HTML DOM ","{html.png}","docs/HTML"],                                                          
     "ECMAScript"  =>["Ngorei ECMAScript","{js.png}","docs/Javascript"],                                               
     "React Native"  =>["Ngorei React ","{react.png}","docs/React"],                                                   
     "Framework7"  =>["Ngorei Framework7","{Framework7.svg}","docs/F7"],                                               
     "DevTools"  =>["Ngorei Storage","{googel.png}","docs/DevTools"],                                                  
     "Firebase"  =>["Ngorei firebase","{firebase.png}","docs/Firebase"],                                               
     "Datatables"  =>["Ngorei Datatables","{Datatables.png}","docs/Datatables"],                                       
     "Chart"  =>["Ngorei Chart","{chart.png}","docs/Chart"],                                                           
     "Vue"  =>["Ngorei  Vue","{vue2.png}","docs/Vue"],                                                                 
     "Wolf05"  =>["Ngorei  OOP","{wolf05.png}","docs/Oop"],                                                            
   ],                                                                                                                  
   "html_content"    =>[                                                                                               
     "Atribute"  =>["docs/HTML/Content#Atribute","icon",""],                                                           
     "Stack Group"  =>["docs/HTML/Content#stackGroup","icon",""],                                                      
     "Container"  =>["docs/HTML/Content#Container","icon",""],                                                         
     "Search"  =>["docs/HTML/Content#Search","icon",""],                                                               
     "Pagination"  =>["docs/HTML/Content#Pagination","icon",""],                                                       
     "Dropdown"  =>["docs/HTML/Content#Dropdown","icon",""],                                                           
     "Menu Selector"  =>["docs/HTML/Content#Selector","icon",""],                                                      
     "Modal PDF"  =>["docs/HTML/Content#domPdf","icon",""],                                                            
     "Prind Raw"  =>["docs/HTML/Content#pridRaw","icon",""],                                                           
     "Modal"  =>["docs/HTML/Content#Modal","icon",""],                                                                 
     "Boostrap"  =>["docs/HTML/Content#Boostrap","icon",""],                                                           
     "Tabel"  =>["docs/HTML/Content#Tabel","icon",""],                                                                 
     "Grid Default"  =>["docs/HTML/Grid#Default","icon",""],                                                           
     "Content"  =>["docs/HTML/Grid#content","icon",""],                                                                
     "Flex"  =>["docs/HTML/Grid#Flex","icon",""],                                                                      
     "Card"  =>["docs/HTML/Grid#Card","icon",""],                                                                      
     "Grid Key"  =>["docs/HTML/Grid#key","icon",""],                                                                   
     "Tab Line"  =>["docs/HTML/Grid#TabLine","icon",""],                                                               
     "Datatables"  =>["docs/HTML/Grid#datatables","icon",""],                                                          
     "Grid Form"  =>["docs/HTML/Grid#From","icon",""],                                                                 
     "From"  =>["docs/HTML/From#From","icon",""],                                                                      
     "Insert"  =>["docs/HTML/From#Insert","icon",""],                                                                  
     "Update"  =>["docs/HTML/From#Update","icon",""],                                                                  
     "Stack"  =>["docs/HTML/From#Stack","icon",""],                                                                    
     "Delete Permanent"  =>["docs/HTML/From#Permanent","icon",""],                                                     
     "Delete Temporarily"  =>["docs/HTML/From#Temporarily","icon",""],                                                 
     "Upload Images"  =>["docs/HTML/From#Images","icon",""],                                                           
     "Upload Document"  =>["docs/HTML/From#Document","icon",""],                                                       
     "Import Excel"  =>["docs/HTML/From#import","icon",""],                                                            
     "Fetch Eksternal"  =>["docs/HTML/Content#Fetch","icon",""],                                                       
     "Read DOM"  =>["docs/HTML/Read","icon",""],                                                                       
   ],                                                                                                                  
   "html_components"    =>[                                                                                            
     "Picons"  =>["docs/HTML/components/icon#picons","icon",""],                                                       
     "Themify Icons"  =>["docs/HTML/components/icon#themify","icon",""],                                               
     "Icon Feather"  =>["docs/HTML/components/icon#iconFeather","icon",""],                                            
     "MDI Icons"  =>["docs/HTML/components/icon#mdi","icon",""],                                                       
     "Feather"  =>["docs/HTML/components/icon#feather","icon",""],                                                     
     "MS Icon"  =>["docs/HTML/components/icon#msIcon","icon",""],                                                      
     "QRcode"  =>["docs/HTML/components#QRcode","icon",""],                                                            
     "List Group"  =>["docs/HTML/components#listGroup","icon",""],                                                     
     "List"  =>["docs/HTML/components#list","icon",""],                                                                
     "avatar"  =>["docs/HTML/components#avatar","icon",""],                                                            
     "images background"  =>["docs/HTML/components#imagesbackground","icon",""],                                       
     "imagesgroup"  =>["docs/HTML/components#imagesgroup","icon",""],                                                  
     "images toolbar"  =>["docs/HTML/components#imagestoolbar","icon",""],                                             
     "Badges"  =>["docs/HTML/components#Badges","icon",""],                                                            
     "Breadcrumbs"  =>["docs/HTML/components#Breadcrumbs","icon",""],                                                  
     "Card Decks"  =>["docs/HTML/components#CardDecks","icon",""],                                                     
     "Card"  =>["docs/HTML/components#Card","icon",""],                                                                
     "Carousel"  =>["docs/HTML/components#Carousel","icon",""],                                                        
     "Indicators"  =>["docs/HTML/components#CarouselIndicators","icon",""],                                            
     "Caption"  =>["docs/HTML/components#CarouselCaption","icon",""],                                                  
     "Marker"  =>["docs/HTML/components#Marker","icon",""],                                                            
     "Media Object"  =>["docs/HTML/components#Media","icon",""],                                                       
   ],                                                                                                                  
   "html_datatables"    =>[                                                                                            
     "Grid System"  =>["docs/Datatables#grid","icon",""],                                                              
     "From Entri"  =>["docs/Datatables#gridFrom","icon",""],                                                           
     "From Stack"  =>["docs/Datatables#gridFromStack","icon",""],                                                      
     "Select Option"  =>["docs/Datatables#selectData","icon",""],                                                      
     "Column Hide"  =>["docs/Datatables#columnHide","icon",""],                                                        
     "Use Click"  =>["docs/Datatables#useClick","icon",""],                                                            
     "Dropdown"  =>["docs/Datatables#Dropdown","icon",""],                                                             
     "Column Defs"  =>["docs/Datatables#columnDefs","icon",""],                                                        
     "Footer Callback"  =>["docs/Datatables#footerCallback","icon",""],                                                
     "Primary Key"  =>["docs/Datatables#primarykey","icon",""],                                                        
     "Use Devices"  =>["docs/Datatables#useDevices","icon",""],                                                        
     "Getting started"  =>["docs/Datatables#started","icon",""],                                                       
     "Head Tabel"  =>["docs/Datatables#headTabel","icon",""],                                                          
     "From Modal"  =>["docs/Datatables#from","icon",""],                                                               
     "Grid System"  =>["docs/Datatables#gridOne","icon",""],                                                           
     "Column Sheet"  =>["docs/Datatables#sheet","icon",""],                                                            
     "Column Role"  =>["docs/Datatables#search","icon",""],                                                            
   ],                                                                                                                  
   "html_mobile"    =>[                                                                                                
     "App index"  =>["docs/F7#Layout","icon",""],                                                                      
     "Routes General"  =>["docs/F7#Routes","icon",""],                                                                 
     "Object Navigasi"  =>["docs/F7#Navigasi","icon",""],                                                              
     "additional pages"  =>["docs/F7#Pages","icon",""],                                                                
     "Dark Mode"  =>["docs/F7#Mode","icon",""],                                                                        
     "Fetch Eksternal "  =>["docs/F7#Fetch","icon",""],                                                                
     "Fetch HTML DOM"  =>["docs/F7#Dom","icon",""],                                                                    
     "Fetch Object"  =>["docs/F7#Object","icon",""],                                                                   
   ],                                                                                                                  
   "html_mobilecomponents"    =>[                                                                                      
     "Action Sheet"  =>["docs/F7/pages#action-sheet","/action-sheet/",""],                                             
     "Columns"  =>["docs/F7/pages#columns","/columns/",""],                                                            
     "Dialog"  =>["docs/F7/pages#dialog","/dialog/",""],                                                               
     "Icons"  =>["docs/F7/pages#icons","/icons/",""],                                                                  
     "infinite Scroll"  =>["docs/F7/pages#infinite-scroll","/infinite-scroll/",""],                                    
     "Notification"  =>["docs/F7/pages#notification","/notification/",""],                                             
     "Page"  =>["docs/F7/pages#page","/page/",""],                                                                     
     "Panel"  =>["docs/F7/pages#panel","/panel/",""],                                                                  
     "Photo Browser"  =>["docs/F7/pages#photo-browser","/photo-browser/",""],                                          
     "Popover"  =>["docs/F7/pages#popover","/popover/",""],                                                            
     "Popup"  =>["docs/F7/pages#popup","/popup/",""],                                                                  
     "Pull to refresh"  =>["docs/F7/pages#pull-to-refresh","/pull-to-refresh/",""],                                    
     "Sheet modal"  =>["docs/F7/pages#sheet-modal","/sheet-modal/",""],                                                
     "Swipe to delete"  =>["docs/F7/pages#swipe-to-delete","/swipe-to-delete/",""],                                    
     "Tabs"  =>["docs/F7/pages#tabs","/tabs/",""],                                                                     
     "Text editor"  =>["docs/F7/pages#text-editor","/text-editor/",""],                                                
     "Toast"  =>["docs/F7/pages#toast","/toast/",""],                                                                  
     "Tooltip"  =>["docs/F7/pages#tooltip","/tooltip/",""],                                                            
     "Typography"  =>["docs/F7/pages#typography","/typography/",""],                                                   
     "Accordion"  =>["docs/F7/pages#accordion","/accordion/",""],                                                      
     "Album list"  =>["docs/F7/pages#album-list","/album-list/",""],                                                   
     "Author list"  =>["docs/F7/pages#author-list","/author-list/",""],                                                
     "Badge"  =>["docs/F7/pages#badge","/badge/",""],                                                                  
     "Button"  =>["docs/F7/pages#button","/button/",""],                                                               
     "Checkbox"  =>["docs/F7/pages#checkbox","/checkbox/",""],                                                         
     "Card"  =>["docs/F7/pages#card","/card/",""],                                                                     
     "Card Footer"  =>["docs/F7/pages#card-footer","/card-footer/",""],                                                
     "Card Big Footer"  =>["docs/F7/pages#card-big-footer","/card-big-footer/",""],                                    
     "Comments"  =>["docs/F7/pages#comments","/comments/",""],                                                         
     "Event list"  =>["docs/F7/pages#event-list","/event-list/",""],                                                   
     "History timeline"  =>["docs/F7/pages#history-timeline","/history-timeline/",""],                                 
     "Information block"  =>["docs/F7/pages#information-block","/information-block/",""],                              
     "Link banner"  =>["docs/F7/pages#link-banner","/link-banner/",""],                                                
     "list"  =>["docs/F7/pages#list","/list/",""],                                                                     
     "List icon"  =>["docs/F7/pages#list-icon","/list-icon/",""],                                                      
     "Picker"  =>["docs/F7/pages#picker","/picker/",""],                                                               
     "Post list"  =>["docs/F7/pages#post-list","/post-list/",""],                                                      
     "Preloader"  =>["docs/F7/pages#preloader","/preloader/",""],                                                      
     "Progress bar"  =>["docs/F7/pages#progress-bar","/progress-bar/",""],                                             
     "Radio"  =>["docs/F7/pages#radio","/radio/",""],                                                                  
     "Range slider"  =>["docs/F7/pages#range-slider","/range-slider/",""],                                             
     "Rating"  =>["docs/F7/pages#rating","/rating/",""],                                                               
     "Slider cards"  =>["docs/F7/pages#slider-cards","/slider-cards/",""],                                             
     "Slider cards footer"  =>["docs/F7/pages#slider-cards-footer","/slider-cards-footer/",""],                        
     "Slider categories"  =>["docs/F7/pages#slider-categories","/slider-categories/",""],                              
     "Slider authors"  =>["docs/F7/pages#slider-authors","/slider-authors/",""],                                       
     "Slider albums"  =>["docs/F7/pages#slider-albums","/slider-albums/",""],                                          
     "Slider movies"  =>["docs/F7/pages#slider-movies","/slider-movies/",""],                                          
     "Stepper"  =>["docs/F7/pages#stepper","/stepper/",""],                                                            
     "Stocks"  =>["docs/F7/pages#stocks","/stocks/",""],                                                               
     "Text input"  =>["docs/F7/pages#text-input","/text-input/",""],                                                   
     "Ticket"  =>["docs/F7/pages#ticket","/ticket/",""],                                                               
     "Toggle button"  =>["docs/F7/pages#toggle-button","/toggle-button/",""],                                          
     "Signup"  =>["docs/F7/pages#signup","/signup/",""],                                                               
     "Signin"  =>["docs/F7/pages#signin","/signin/",""],                                                               
     "Forgot password"  =>["docs/F7/pages#forgot-password","/forgot-password/",""],                                    
     "Messages"  =>["docs/F7/pages#messages","/messages/",""],                                                         
     "Chat"  =>["docs/F7/pages#chat","/chat/",""],                                                                     
     "Single"  =>["docs/F7/pages#single","/single/",""],                                                               
     "Create post"  =>["docs/F7/pages#create-post","/create-post/",""],                                                
     "Movie"  =>["docs/F7/pages#movie","/movie/",""],                                                                  
     "Album"  =>["docs/F7/pages#album","/album/",""],                                                                  
     "Calendar"  =>["docs/F7/pages#calendar","/calendar/",""],                                                         
     "Help center"  =>["docs/F7/pages#help-center","/help-center/",""],                                                
     "Contact"  =>["docs/F7/pages#contact","/contact/",""],                                                            
     "Settings"  =>["docs/F7/pages#settings","/settings/",""],                                                         
     "Categories"  =>["docs/F7/pages#categories","/categories/",""],                                                   
     "Profile"  =>["docs/F7/pages#profile","/profile/",""],                                                            
     "Search"  =>["docs/F7/pages#search","/search/",""],                                                               
     "Notifications"  =>["docs/F7/pages#notifications","/notifications/",""],                                          
     "Onboarding"  =>["docs/F7/pages#onboarding","/onboarding/",""],                                                   
   ],                                                                                                                  
   "db_php"    =>[                                                                                                     
     "Datetime"  =>["docs/Oop#datetime","icon",""],                                                                    
     "Text"  =>["docs/Oop#text","icon",""],                                                                            
     "Cookie"  =>["docs/Oop#cookie","icon",""],                                                                        
     "Encryption"  =>["docs/Oop#encryption","icon",""],                                                                
     "Validation"  =>["docs/Oop#validation","icon",""],                                                                
     "Images"  =>["docs/Oop#resizeimages","icon",""],                                                                  
     "Pre Code"  =>["docs/Oop#precode","icon",""],                                                                     
     "MangoDB"  =>["docs/Oop#MangoDB","icon",""],                                                                      
     "Postgre SQL"  =>["docs/Oop#PostgreSQL","icon",""],                                                               
     "Python"  =>["docs/Oop#Python","icon",""],                                                                        
     "SQL Lite"  =>["docs/Oop#SQLlite","icon",""],                                                                     
     "Face Detector"  =>["docs/Oop#Facedetector","icon",""],                                                           
     "TOCR"  =>["docs/Oop#TOCR","icon",""],                                                                            
     "NIK"  =>["docs/Oop#NIK","icon",""],                                                                              
   ],                                                                                                                  
  ];                                                                                                                   
  $hashtag=[                                                                                               
   "zero_config"    =>[                                                                                    
     "Struktur"  =>["docs/intro/configurasi/doctype","#doctype","icon"],                                   
     "Struktur Assets"  =>["docs/intro/configurasi/Assets","#Assets","icon"],                              
     "Assets Condisi"  =>["docs/intro/configurasi/Condisi","#Condisi","icon"],                             
     "Base URL"  =>["docs/intro/configurasi/Base","#Base","icon"],                                         
     "Import Module"  =>["docs/intro/configurasi/Import","#Import","icon"],                                
     "Navbar"  =>["docs/intro/configurasi/Navbar","#Navbar","icon"],                                       
     "Include Path"  =>["docs/intro/configurasi/Include","#Include","icon"],                               
   ],                                                                                                      
   "app_config"    =>[                                                                                     
     "Url Root"  =>["docs/intro/configurasi/root","#root","icon"],                                         
     "Database"  =>["docs/intro/configurasi/database","#database","icon"],                                 
   ],                                                                                                      
   "object_router"    =>[                                                                                  
     "Object"  =>["docs/intro/Router/Object","#Object","icon"],                                            
     "Hashtag"  =>["docs/intro/Router/Hashtag","#Hashtag","icon"],                                         
     "Onclick"  =>["docs/intro/Router/Onclick","#Onclick","icon"],                                         
     "Pages"  =>["docs/intro/Router/Pages","#Pages","icon"],                                               
   ],                                                                                                      
   "db_storage"    =>[                                                                                     
     "Localstorage"  =>["docs/DevTools/storage","#storage","icon"],                                        
     "Cookie"  =>["docs/DevTools/Cookie","#Cookie","icon"],                                                
     "indexedDB"  =>["docs/DevTools/indexedDB","#indexedDB","icon"],                                       
   ],                                                                                                      
   "db_firebase"    =>[                                                                                    
     "For Each"  =>["docs/DevTools/Firebase=forEach","#Firebase=forEach","icon"],                          
     "Insert"  =>["docs/DevTools/Firebase=Insert","#Firebase=Insert","icon"],                              
     "Update"  =>["docs/DevTools/Firebase=Update","#Firebase=Update","icon"],                              
     "Delete"  =>["docs/DevTools/Firebase=Delete","#Firebase=Delete","icon"],                              
     "Select"  =>["docs/DevTools/Firebase=Select","#Firebase=Select","icon"],                              
     "Push"  =>["docs/DevTools/Firebase=Push","#Firebase=Push","icon"],                                    
     "Limit"  =>["docs/DevTools/Firebase=Limit","#Firebase=Limit","icon"],                                 
   ],                                                                                                      
   "set_firebase"    =>[                                                                                   
     "For Each"  =>["docs/Firebase/Firebase=forEach","#Firebase=forEach","icon"],                          
     "Insert"  =>["docs/Firebase/Firebase=Insert","#Firebase=Insert","icon"],                              
     "Update"  =>["docs/Firebase/Firebase=Update","#Firebase=Update","icon"],                              
     "Delete"  =>["docs/Firebase/Firebase=Delete","#Firebase=Delete","icon"],                              
     "Select"  =>["docs/Firebase/Firebase=Select","#Firebase=Select","icon"],                              
     "Push"  =>["docs/Firebase/Firebase=Push","#Firebase=Push","icon"],                                    
     "Limit"  =>["docs/Firebase/Firebase=Limit","#Firebase=Limit","icon"],                                 
   ],                                                                                                      
   "db_api"    =>[                                                                                         
     "Create Auth"  =>["docs/ApiReference/Auth","#Auth","icon"],                                           
     "Package"  =>["docs/ApiReference/Package","#Package","icon"],                                         
     "Get Token"  =>["docs/ApiReference/Token","#Token","icon"],                                           
     "Read Data"  =>["docs/ApiReference/Read","#Read","icon"],                                             
     "Datatables"  =>["docs/ApiReference/Datatables","#Datatables","icon"],                                
     "Add Query"  =>["docs/ApiReference/Add","#Add","icon"],                                               
     "Data Entri"  =>["docs/ApiReference/Entri","#Entri","icon"],                                          
     "Data Update"  =>["docs/ApiReference/Update","#Update","icon"],                                       
     "Upload Images"  =>["docs/ApiReference/Images","#Images","icon"],                                     
     "Upload File"  =>["docs/ApiReference/File","#File","icon"],                                           
     "Delete"  =>["docs/ApiReference/Delete","#Delete","icon"],                                            
     "Office"  =>["docs/ApiReference-officeOffice","#Office","icon"],                                      
   ],                                                                                                      
   "db_office"    =>[                                                                                      
     "Get Token"  =>["docs/ApiReference-office/Token","#Token","icon"],                                    
     "Property"  =>["docs/ApiReference-office/Property","#Property","icon"],                               
     "Pdf"  =>["docs/ApiReference-office/Pdf","#Pdf","icon"],                                              
     "Ppt"  =>["docs/ApiReference-office/Ppt","#Ppt","icon"],                                              
     "Xlsx"  =>["docs/ApiReference-office/Xlsx","#Xlsx","icon"],                                           
     "Docx"  =>["docs/ApiReference-office/Docx","#Docx","icon"],                                           
   ],                                                                                                      
   "db_modules"    =>[                                                                                     
     "Text"  =>["docs/Javascript/Text","#Text","icon"],                                                    
     "Date Time"  =>["docs/Javascript/DateTime","#DateTime","icon"],                                       
     "Encode"  =>["docs/Javascript/Decode","#Decode","icon"],                                              
     "OnClick"  =>["docs/Javascript/OnClick","#OnClick","icon"],                                           
     "Get History"  =>["docs/Javascript/History","#History","icon"],                                       
     "User Agent"  =>["docs/Javascript/userAgent","#userAgent","icon"],                                    
     "Location"  =>["docs/Javascript/Location","#Location","icon"],                                        
     "Shortcut"  =>["docs/Javascript/Shortcut","#Shortcut","icon"],                                        
     "SetLink"  =>["docs/Javascript/SetLink","#SetLink","icon"],                                           
   ],                                                                                                      
   "db_dateTime"    =>[                                                                                    
     "Date Hari"  =>["docs/Javascript/DateTime=setDateTime=hari","#DateTime=setDateTime=hari","icon"],     
     "Date Bulan"  =>["docs/Javascript/DateTime=setDateTime=bulan","#DateTime=setDateTime=bulan","icon"],  
     "Date Tahun"  =>["docs/Javascript/DateTime=setDateTime=tahun","#DateTime=setDateTime=tahun","icon"],  
     "Date Jam"  =>["docs/Javascript/DateTime=setDateTime=jam","#DateTime=setDateTime=jam","icon"],        
     "Date EN"  =>["docs/Javascript/DateTime=setDateTime=EN","#DateTime=setDateTime=EN","icon"],           
     "Date DIN"  =>["docs/Javascript/DateTime=setDateTime=DIN","#DateTime=setDateTime=DIN","icon"],        
     "Date IN"  =>["docs/Javascript/DateTime=setDateTime=IN","#DateTime=setDateTime=IN","icon"],           
     "Date IND"  =>["docs/Javascript/DateTime=setDateTime=IND","#DateTime=setDateTime=IND","icon"],        
     "Date Day"  =>["docs/Javascript/DateTime=setDateTime=Day","#DateTime=setDateTime=Day","icon"],        
     "Date Month"  =>["docs/Javascript/DateTime=setDateTime=Month","#DateTime=setDateTime=Month","icon"],  
     "Date Year"  =>["docs/Javascript/DateTime=setDateTime=Year","#DateTime=setDateTime=Year","icon"],     
     "Date Bln"  =>["docs/Javascript/DateTime=setDateTime=Bln","#DateTime=setDateTime=Bln","icon"],        
     "Date Time"  =>["docs/Javascript/DateTime=setDateTime=time","#DateTime=setDateTime=time","icon"],     
     "Date Time dmy"  =>["docs/Javascript/DateTime=setDateTime=dmy","#DateTime=setDateTime=dmy","icon"],   
     "Time v"  =>["docs/Javascript/DateTime=setDateTime=v","#DateTime=setDateTime=v","icon"],              
     "Time time"  =>["docs/Javascript/DateTime=setDateTime=timex","#DateTime=setDateTime=timex","icon"],   
     "Time Day"  =>["docs/Javascript/DateTime=setDateTime=day","#DateTime=setDateTime=day","icon"],        
     "Time Month"  =>["docs/Javascript/DateTime=setDateTime=month","#DateTime=setDateTime=month","icon"],  
     "Time Year"  =>["docs/Javascript/DateTime=setDateTime=year","#DateTime=setDateTime=year","icon"],     
   ],                                                                                                      
   "db_encode"    =>[                                                                                      
     "Set Decode"  =>["docs/Javascript/Decode=setDecode","#Decode=setDecode","icon"],                      
     "Set Token"  =>["docs/Javascript/Decode=setToken","#Decode=setToken","icon"],                         
     "Get Token"  =>["docs/Javascript/Decode=getToken","#Decode=getToken","icon"],                         
   ],                                                                                                      
   "db_onclick"    =>[                                                                                     
     "Insert"  =>["docs/Javascript/OnClick=insert","#OnClick=insert","icon"],                              
     "Update"  =>["docs/Javascript/OnClick=update","#OnClick=update","icon"],                              
     "Stack"  =>["docs/Javascript/OnClick=stack","#OnClick=stack","icon"],                                 
     "Delete Permananet"  =>["docs/Javascript/OnClick=permananet","#OnClick=permananet","icon"],           
     "Delete Temporarily"  =>["docs/Javascript/OnClick=temporarily","#OnClick=temporarily","icon"],        
     "Upload Images"  =>["docs/Javascript/OnClick=images","#OnClick=images","icon"],                       
     "Upload Document"  =>["docs/Javascript/OnClick=documents","#OnClick=documents","icon"],               
     "Import Excel"  =>["docs/Javascript/OnClick=import","#OnClick=import","icon"],                        
     "Modal"  =>["docs/Javascript/OnClick=modals","#OnClick=modals","icon"],                               
     "Plugin"  =>["docs/Javascript/OnClick=plugis","#OnClick=plugis","icon"],                              
     "Target"  =>["docs/Javascript/OnClick=targets","#OnClick=targets","icon"],                            
     "Dom Pdf"  =>["docs/Javascript/OnClick=dopdf","#OnClick=dopdf","icon"],                               
     "Prind Raw"  =>["docs/Javascript/OnClick=prindraw","#OnClick=prindraw","icon"],                       
     "Route"  =>["docs/Javascript/OnClick=routes","#OnClick=routes","icon"],                               
     "Dialog"  =>["docs/Javascript/OnClick=dialogs","#OnClick=dialogs","icon"],                            
     "Link Route"  =>["docs/Javascript/OnClick=lroute","#OnClick=lroute","icon"],                          
     "Link Sign"  =>["docs/Javascript/OnClick=lsign","#OnClick=lsign","icon"],                             
   ],                                                                                                      
   "db_text"    =>[                                                                                        
     "Romawi"  =>["docs/Javascript/Text=romawi","#Text=romawi","icon"],                                    
     "Readmore"  =>["docs/Javascript/Text=readmore","#Text=readmore","icon"],                              
     "Substr"  =>["docs/Javascript/Text=substr","#Text=substr","icon"],                                    
     "Split"  =>["docs/Javascript/Text=setSplit","#Text=setSplit","icon"],                                 
     "Replace"  =>["docs/Javascript/Text=replace","#Text=replace","icon"],                                 
     "Rupiah"  =>["docs/Javascript/Text=rupiah","#Text=rupiah","icon"],                                    
     "Terbilang"  =>["docs/Javascript/Text=terbilang","#Text=terbilang","icon"],                           
     "Explode"  =>["docs/Javascript/Text=explode","#Text=explode","icon"],                                 
   ],                                                                                                      
  ];                                                                                                       
