<?php
  error_reporting(0);                                                                    
  $routeLink=[                                                                           
   "ecosystem"    =>[                                                                    
     "Download"  =>["Github@ngorei ","picons-106","docs/intro/Download"],                
     "Installation"  =>["NPM tatiye","picons-193","docs/intro/Installation"],            
     "Configurasi"  =>["Package &amp; Database","picons-194","docs/intro/Configurasi"],  
     "License key"  =>["Trial 25-day","picons-114","docs/intro/License"],                
     "Routes"  =>["Links &amp; Pages","picons-359","docs/intro/Router"],                 
     "API Reference"  =>["Fetch Data","picons-359","docs/ApiReference"],                 
   ],                                                                                    
   "rich"    =>[                                                                         
     "HTML"  =>["Ngorei HTML DOM ","{html.png}","docs/HTML"],                            
     "ECMAScript"  =>["Ngorei ECMAScript","{js.png}","docs/Javascript"],                 
     "iOS,Android"  =>["Ngorei React ","{react.png}","docs/React"],                      
     "Framework7"  =>["Ngorei Framework7","{Framework7.svg}","docs/F7"],                 
     "DevTools"  =>["Ngorei Storage","{googel.png}","docs/DevTools"],                    
     "Firebase"  =>["Ngorei firebase","{firebase.png}","docs/Firebase"],                 
     "Datatables"  =>["Ngorei Datatables","{Datatables.png}","docs/Datatables"],         
     "Chart"  =>["Ngorei Chart","{chart.png}","docs/Chart"],                             
   ],                                                                                    
   "navigasi"    =>[                                                                     
     "Action Sheet"  =>["components/action-sheet","icon",""],                            
     "Columns"  =>["components/columns","icon",""],                                      
     "Dialog"  =>["components/dialog","icon",""],                                        
     "Icons"  =>["components/icons","icon",""],                                          
     "infinite Scroll"  =>["components/infinite-scroll","icon",""],                      
     "Notification"  =>["components/notification","icon",""],                            
     "Page"  =>["components/page","icon",""],                                            
     "Panel"  =>["components/panel","icon",""],                                          
     "Photo Browser"  =>["components/photo-browser","icon",""],                          
     "Popover"  =>["components/popover","icon",""],                                      
     "Popup"  =>["components/popup","icon",""],                                          
     "Pull to refresh"  =>["components/pull-to-refresh","icon",""],                      
     "Sheet modal"  =>["components/sheet-modal","icon",""],                              
     "Swipe to delete"  =>["components/swipe-to-delete","icon",""],                      
     "Tabs"  =>["components/tabs","icon",""],                                            
     "Text editor"  =>["components/text-editor","icon",""],                              
     "Toast"  =>["components/toast","icon",""],                                          
     "Tooltip"  =>["components/tooltip","icon",""],                                      
     "Typography"  =>["components/typography","icon",""],                                
     "Accordion"  =>["components/accordion","icon",""],                                  
     "Album list"  =>["components/album-list","icon",""],                                
     "Author list"  =>["components/author-list","icon",""],                              
     "Badge"  =>["components/badge","icon",""],                                          
     "Button"  =>["components/button","icon",""],                                        
     "Checkbox"  =>["components/checkbox","icon",""],                                    
     "Card"  =>["components/card","icon",""],                                            
     "Card Footer"  =>["components/card-footer","icon",""],                              
     "Card Big Footer"  =>["components/card-big-footer","icon",""],                      
     "Comments"  =>["components/comments","icon",""],                                    
     "Event list"  =>["components/event-list","icon",""],                                
     "History timeline"  =>["components/history-timeline","icon",""],                    
     "Information block"  =>["components/information-block","icon",""],                  
     "Link banner"  =>["components/link-banner","icon",""],                              
     "list"  =>["components/list","icon",""],                                            
     "List icon"  =>["components/list-icon","icon",""],                                  
     "Picker"  =>["components/picker","icon",""],                                        
     "Post list"  =>["components/post-list","icon",""],                                  
     "Preloader"  =>["components/preloader","icon",""],                                  
     "Progress bar"  =>["components/progress-bar","icon",""],                            
     "Radio"  =>["components/radio","icon",""],                                          
     "Range slider"  =>["components/range-slider","icon",""],                            
     "Rating"  =>["components/rating","icon",""],                                        
     "Slider cards"  =>["components/slider-cards","icon",""],                            
     "Slider cards footer"  =>["components/slider-cards-footer","icon",""],              
     "Slider categories"  =>["components/slider-categories","icon",""],                  
     "Slider authors"  =>["components/slider-authors","icon",""],                        
     "Slider albums"  =>["components/slider-albums","icon",""],                          
     "Slider movies"  =>["components/slider-movies","icon",""],                          
     "Stepper"  =>["components/stepper","icon",""],                                      
     "Stocks"  =>["components/stocks","icon",""],                                        
     "Text input"  =>["components/text-input","icon",""],                                
     "Ticket"  =>["components/ticket","icon",""],                                        
     "Toggle button"  =>["components/toggle-button","icon",""],                          
     "Signup"  =>["components/signup","icon",""],                                        
     "Signin"  =>["components/signin","icon",""],                                        
     "Forgot password"  =>["components/forgot-password","icon",""],                      
     "Messages"  =>["components/messages","icon",""],                                    
     "Chat"  =>["components/chat","icon",""],                                            
     "Single"  =>["components/single","icon",""],                                        
     "Create post"  =>["components/create-post","icon",""],                              
     "Movie"  =>["components/movie","icon",""],                                          
     "Album"  =>["components/album","icon",""],                                          
     "Calendar"  =>["components/calendar","icon",""],                                    
     "Help center"  =>["components/help-center","icon",""],                              
     "Contact"  =>["components/contact","icon",""],                                      
     "Settings"  =>["pages/settings","icon",""],                                         
     "Categories"  =>["components/categories","icon",""],                                
     "Profile"  =>["components/profile","icon",""],                                      
     "Search"  =>["components/search","icon",""],                                        
     "Notifications"  =>["components/notifications","icon",""],                          
     "Onboarding"  =>["components/onboarding","icon",""],                                
     "components"  =>["pages/components","icon",""],                                     
     "ecosystem"  =>["pages/ecosystem","icon",""],                                       
     "HTML"  =>["docs/HTML","icon",""],                                                  
     "ECMAScript"  =>["docs/Javascript","icon",""],                                      
     "iOS,Android"  =>["docs/React","icon",""],                                          
     "Framework7"  =>["docs/F7","icon",""],                                              
     "DevTools"  =>["docs/DevTools","icon",""],                                          
     "Firebase"  =>["docs/Firebase","icon",""],                                          
     "Datatables"  =>["docs/Datatables","icon",""],                                      
     "Chart"  =>["docs/Chart","icon",""],                                                
     "Download"  =>["docs/intro/Download","icon",""],                                    
     "License key"  =>["docs/intro/License","icon",""],                                  
     "Installation"  =>["docs/intro/Installation","icon",""],                            
     "Configurasi"  =>["docs/intro/Configurasi","icon",""],                              
     "Routes"  =>["docs/intro/Router","icon",""],                                        
     "API Reference"  =>["docs/ApiReference","icon",""],                                 
     "histor"  =>["pages/histor","icon",""],                                             
   ],                                                                                    
   "components"    =>[                                                                   
     "Action Sheet"  =>["components/action-sheet","icon",""],                            
     "Columns"  =>["components/columns","icon",""],                                      
     "Dialog"  =>["components/dialog","icon",""],                                        
     "Icons"  =>["components/icons","icon",""],                                          
     "infinite Scroll"  =>["components/infinite-scroll","icon",""],                      
     "Notification"  =>["components/notification","icon",""],                            
     "Page"  =>["components/page","icon",""],                                            
     "Panel"  =>["components/panel","icon",""],                                          
     "Photo Browser"  =>["components/photo-browser","icon",""],                          
     "Popover"  =>["components/popover","icon",""],                                      
     "Popup"  =>["components/popup","icon",""],                                          
     "Pull to refresh"  =>["components/pull-to-refresh","icon",""],                      
     "Sheet modal"  =>["components/sheet-modal","icon",""],                              
     "Swipe to delete"  =>["components/swipe-to-delete","icon",""],                      
     "Tabs"  =>["components/tabs","icon",""],                                            
     "Text editor"  =>["components/text-editor","icon",""],                              
     "Toast"  =>["components/toast","icon",""],                                          
     "Tooltip"  =>["components/tooltip","icon",""],                                      
     "Typography"  =>["components/typography","icon",""],                                
     "Accordion"  =>["components/accordion","icon",""],                                  
     "Album list"  =>["components/album-list","icon",""],                                
     "Author list"  =>["components/author-list","icon",""],                              
     "Badge"  =>["components/badge","icon",""],                                          
     "Button"  =>["components/button","icon",""],                                        
     "Checkbox"  =>["components/checkbox","icon",""],                                    
     "Card"  =>["components/card","icon",""],                                            
     "Card Footer"  =>["components/card-footer","icon",""],                              
     "Card Big Footer"  =>["components/card-big-footer","icon",""],                      
     "Comments"  =>["components/comments","icon",""],                                    
     "Event list"  =>["components/event-list","icon",""],                                
     "History timeline"  =>["components/history-timeline","icon",""],                    
     "Information block"  =>["components/information-block","icon",""],                  
     "Link banner"  =>["components/link-banner","icon",""],                              
     "list"  =>["components/list","icon",""],                                            
     "List icon"  =>["components/list-icon","icon",""],                                  
     "Picker"  =>["components/picker","icon",""],                                        
     "Post list"  =>["components/post-list","icon",""],                                  
     "Preloader"  =>["components/preloader","icon",""],                                  
     "Progress bar"  =>["components/progress-bar","icon",""],                            
     "Radio"  =>["components/radio","icon",""],                                          
     "Range slider"  =>["components/range-slider","icon",""],                            
     "Rating"  =>["components/rating","icon",""],                                        
     "Slider cards"  =>["components/slider-cards","icon",""],                            
     "Slider cards footer"  =>["components/slider-cards-footer","icon",""],              
     "Slider categories"  =>["components/slider-categories","icon",""],                  
     "Slider authors"  =>["components/slider-authors","icon",""],                        
     "Slider albums"  =>["components/slider-albums","icon",""],                          
     "Slider movies"  =>["components/slider-movies","icon",""],                          
     "Stepper"  =>["components/stepper","icon",""],                                      
     "Stocks"  =>["components/stocks","icon",""],                                        
     "Text input"  =>["components/text-input","icon",""],                                
     "Ticket"  =>["components/ticket","icon",""],                                        
     "Toggle button"  =>["components/toggle-button","icon",""],                          
     "Signup"  =>["components/signup","icon",""],                                        
     "Signin"  =>["components/signin","icon",""],                                        
     "Forgot password"  =>["components/forgot-password","icon",""],                      
     "Messages"  =>["components/messages","icon",""],                                    
     "Chat"  =>["components/chat","icon",""],                                            
     "Single"  =>["components/single","icon",""],                                        
     "Create post"  =>["components/create-post","icon",""],                              
     "Movie"  =>["components/movie","icon",""],                                          
     "Album"  =>["components/album","icon",""],                                          
     "Calendar"  =>["components/calendar","icon",""],                                    
     "Help center"  =>["components/help-center","icon",""],                              
     "Contact"  =>["components/contact","icon",""],                                      
     "Settings"  =>["pages/settings","icon",""],                                         
     "Categories"  =>["components/categories","icon",""],                                
     "Profile"  =>["components/profile","icon",""],                                      
     "Search"  =>["components/search","icon",""],                                        
     "Notifications"  =>["components/notifications","icon",""],                          
     "Onboarding"  =>["components/onboarding","icon",""],                                
   ],                                                                                    
   "doc"    =>[                                                                          
     "Download"  =>["docs/download","icon",""],                                          
     "Installation"  =>["docs/installation","icon",""],                                  
     "Zero configuration"  =>["docs/configurasi","icon",""],                             
     "Router"  =>["docs/router","icon",""],                                              
     "API Reference"  =>["docs/rest-api","icon",""],                                     
     "Storage"  =>["docs/Storage","icon",""],                                            
     "Modules"  =>["docs/Modules","icon",""],                                            
     "DOM interfaces"  =>["docs/Dom","icon",""],                                         
     "Components"  =>["docs/components","icon",""],                                      
   ],                                                                                    
   "html_content"    =>[                                                                 
     "Atribute"  =>["docs/HTML/Content#Atribute","icon",""],                             
     "Stack Group"  =>["docs/HTML/Content#stackGroup","icon",""],                        
     "Container"  =>["docs/HTML/Content#Container","icon",""],                           
     "Search"  =>["docs/HTML/Content#Search","icon",""],                                 
     "Pagination"  =>["docs/HTML/Content#Pagination","icon",""],                         
     "Dropdown"  =>["docs/HTML/Content#Dropdown","icon",""],                             
     "Menu Selector"  =>["docs/HTML/Content#Selector","icon",""],                        
     "Modal PDF"  =>["docs/HTML/Content#domPdf","icon",""],                              
     "Prind Raw"  =>["docs/HTML/Content#pridRaw","icon",""],                             
     "Modal"  =>["docs/HTML/Content#Modal","icon",""],                                   
     "Boostrap"  =>["docs/HTML/Content#Boostrap","icon",""],                             
     "Tabel"  =>["docs/HTML/Content#Tabel","icon",""],                                   
     "Grid Default"  =>["docs/HTML/Grid#Default","icon",""],                             
     "Content"  =>["docs/HTML/Grid#content","icon",""],                                  
     "Flex"  =>["docs/HTML/Grid#Flex","icon",""],                                        
     "Card"  =>["docs/HTML/Grid#Card","icon",""],                                        
     "Grid Key"  =>["docs/HTML/Grid#key","icon",""],                                     
     "Tab Line"  =>["docs/HTML/Grid#TabLine","icon",""],                                 
     "Datatables"  =>["docs/HTML/Grid#datatables","icon",""],                            
     "Grid Form"  =>["docs/HTML/Grid#From","icon",""],                                   
     "From"  =>["docs/HTML/From#From","icon",""],                                        
     "Insert"  =>["docs/HTML/From#Insert","icon",""],                                    
     "Update"  =>["docs/HTML/From#Update","icon",""],                                    
     "Stack"  =>["docs/HTML/From#Stack","icon",""],                                      
     "Delete Permanent"  =>["docs/HTML/From#Permanent","icon",""],                       
     "Delete Temporarily"  =>["docs/HTML/From#Temporarily","icon",""],                   
     "Upload Images"  =>["docs/HTML/From#Images","icon",""],                             
     "Upload Document"  =>["docs/HTML/From#Document","icon",""],                         
     "Import Excel"  =>["docs/HTML/From#import","icon",""],                              
   ],                                                                                    
   "html_components"    =>[                                                              
     "Picons"  =>["docs/HTML/components/icon#picons","icon",""],                         
     "Themify Icons"  =>["docs/HTML/components/icon#themify","icon",""],                 
     "Icon Feather"  =>["docs/HTML/components/icon#iconFeather","icon",""],              
     "MDI Icons"  =>["docs/HTML/components/icon#mdi","icon",""],                         
     "Feather"  =>["docs/HTML/components/icon#feather","icon",""],                       
     "MS Icon"  =>["docs/HTML/components/icon#msIcon","icon",""],                        
     "QRcode"  =>["docs/HTML/components#QRcode","icon",""],                              
     "List Group"  =>["docs/HTML/components#listGroup","icon",""],                       
     "List"  =>["docs/HTML/components#list","icon",""],                                  
     "avatar"  =>["docs/HTML/components#avatar","icon",""],                              
     "images background"  =>["docs/HTML/components#imagesbackground","icon",""],         
     "imagesgroup"  =>["docs/HTML/components#imagesgroup","icon",""],                    
     "images toolbar"  =>["docs/HTML/components#imagestoolbar","icon",""],               
     "Badges"  =>["docs/HTML/components#Badges","icon",""],                              
     "Breadcrumbs"  =>["docs/HTML/components#Breadcrumbs","icon",""],                    
     "Card Decks"  =>["docs/HTML/components#CardDecks","icon",""],                       
     "Card"  =>["docs/HTML/components#Card","icon",""],                                  
     "Carousel"  =>["docs/HTML/components#Carousel","icon",""],                          
     "Indicators"  =>["docs/HTML/components#CarouselIndicators","icon",""],              
     "Caption"  =>["docs/HTML/components#CarouselCaption","icon",""],                    
     "Marker"  =>["docs/HTML/components#Marker","icon",""],                              
     "Media Object"  =>["docs/HTML/components#Media","icon",""],                         
   ],                                                                                    
   "db_storage"    =>[                                                                   
     "Localstorage"  =>["docs/DevTools#storage","icon",""],                              
     "Cookie"  =>["docs/DevTools#Cookie","icon",""],                                     
     "indexedDB"  =>["docs/DevTools#indexedDB","icon",""],                               
   ],                                                                                    
   "html_datatables"    =>[                                                              
     "Grid System"  =>["docs/Datatables#grid","icon",""],                                
     "From Entri"  =>["docs/Datatables#gridFrom","icon",""],                             
     "From Stack"  =>["docs/Datatables#gridFromStack","icon",""],                        
     "Select Option"  =>["docs/Datatables#selectData","icon",""],                        
     "Column Hide"  =>["docs/Datatables#columnHide","icon",""],                          
     "Use Click"  =>["docs/Datatables#useClick","icon",""],                              
     "Dropdown"  =>["docs/Datatables#Dropdown","icon",""],                               
     "Column Defs"  =>["docs/Datatables#columnDefs","icon",""],                          
     "Footer Callback"  =>["docs/Datatables#footerCallback","icon",""],                  
     "Primary Key"  =>["docs/Datatables#primarykey","icon",""],                          
     "Use Devices"  =>["docs/Datatables#useDevices","icon",""],                          
     "Getting started"  =>["docs/Datatables#started","icon",""],                         
     "Head Tabel"  =>["docs/Datatables#headTabel","icon",""],                            
     "From Modal"  =>["docs/Datatables#from","icon",""],                                 
     "Grid System"  =>["docs/Datatables#gridOne","icon",""],                             
     "Column Sheet"  =>["docs/Datatables#sheet","icon",""],                              
     "Column Role"  =>["docs/Datatables#search","icon",""],                              
   ],                                                                                    
   "html_react"    =>[                                                                   
     "useUid"  =>["docs/React/useUid","icon",""],                                        
     "Feather"  =>["docs/React/FeatherIcon","icon",""],                                  
     "Material Community"  =>["docs/React/MaterialCommunityIcons","icon",""],            
     "useHandelCreate"  =>["docs/React/useHandelCreate","icon",""],                      
     "useHandelList"  =>["docs/React/useHandelList","icon",""],                          
     "useHandelHttp"  =>["docs/React/useHandelHttp","icon",""],                          
     "Get List item"  =>["docs/React/getList","icon",""],                                
     "List map"  =>["docs/React/getListmap","icon",""],                                  
     "Search"  =>["docs/React/getListSearch","icon",""],                                 
     "Pagination"  =>["docs/React/getListPagination","icon",""],                         
     "Modal"  =>["docs/React/Modal","icon",""],                                          
     "Bulder"  =>["docs/React/Bulder","icon",""],                                        
     "Text Input"  =>["docs/React/TextInput","icon",""],                                 
     "Select List"  =>["docs/React/SelectList","icon",""],                               
     "Date Picker"  =>["docs/React/datePicker","icon",""],                               
     "Time Picker"  =>["docs/React/timePicker","icon",""],                               
     "Validasi"  =>["docs/React/validasi","icon",""],                                    
     "Camera"  =>["docs/React/upCamera","icon",""],                                      
     "Galery"  =>["docs/React/upGaler","icon",""],                                       
   ],                                                                                    
   "html_chart"    =>[                                                                   
     "Bar Metrics"  =>["docs/Chart#chartBar","icon",""],                                 
     "Peity"  =>["docs/Chart#Peity","icon",""],                                          
     "Horizontal"  =>["docs/Chart#horizontalBar","icon",""],                             
     "Flot Char"  =>["docs/Chart#flotChar","icon",""],                                   
     "Satisfaction"  =>["docs/Chart#Satisfaction","icon",""],                            
     "Points"  =>["docs/Chart#Points","icon",""],                                        
     "Received"  =>["docs/Chart#Received","icon",""],                                    
     "Actual"  =>["docs/Chart#Actual","icon",""],                                        
     "Stack"  =>["docs/Chart#stack","icon",""],                                          
     "Arrowup"  =>["docs/Chart#arrowu","icon",""],                                       
     "Chart Five"  =>["docs/Chart#Chartfive","icon",""],                                 
     "Twelve"  =>["docs/Chart#twelve","icon",""],                                        
     "Currency"  =>["docs/Chart#Currency","icon",""],                                    
     "Markets"  =>["docs/Chart#Markets","icon",""],                                      
     "Sessions"  =>["docs/Chart#Sessions","icon",""],                                    
     "Visits"  =>["docs/Chart#Visits","icon",""],                                        
     "Traffic"  =>["docs/Chart#Traffic","icon",""],                                      
     "Watchlist"  =>["docs/Chart#Watchlist","icon",""],                                  
     "Line Chart"  =>["docs/Chart#LineChart","icon",""],                                 
   ],                                                                                    
   "html_mobile"    =>[                                                                  
     "App index"  =>["docs/F7#Layout","icon",""],                                        
     "Routes General"  =>["docs/F7#Routes","icon",""],                                   
     "Object Navigasi"  =>["docs/F7#Navigasi","icon",""],                                
     "additional pages"  =>["docs/F7#Pages","icon",""],                                  
     "Dark Mode"  =>["docs/F7#Mode","icon",""],                                          
     "Fetch Eksternal "  =>["docs/F7#Fetch","icon",""],                                  
     "Fetch HTML DOM"  =>["docs/F7#Dom","icon",""],                                      
     "Fetch Object"  =>["docs/F7#Object","icon",""],                                     
   ],                                                                                    
   "html_mobilecomponents"    =>[                                                        
     "Action Sheet"  =>["docs/pages/features#action-sheet","/action-sheet/",""],         
   ],                                                                                    
   "db_api"    =>[                                                                       
     "Create Auth"  =>["docs/ApiReference#Auth","icon",""],                              
     "Package"  =>["docs/ApiReference#Package","icon",""],                               
     "Get Token"  =>["docs/ApiReference#Token","icon",""],                               
     "Read Data"  =>["docs/ApiReference#Read","icon",""],                                
     "Datatables"  =>["docs/ApiReference#Datatables","icon",""],                         
     "Add Query"  =>["docs/ApiReference#Add","icon",""],                                 
     "Data Entri"  =>["docs/ApiReference#Entri","icon",""],                              
     "Data Update"  =>["docs/ApiReference#Update","icon",""],                            
     "Upload Images"  =>["docs/ApiReference#Images","icon",""],                          
     "Upload File"  =>["docs/ApiReference#File","icon",""],                              
     "Delete"  =>["docs/ApiReference#Delete","icon",""],                                 
     "Office"  =>["docs/ApiReference-office","Office","icon"],                           
   ],                                                                                    
  ];                                                                                     
  $hashtag=[                                                                                               
   "zero_config"    =>[                                                                                    
     "Struktur"  =>["docs/intro/configurasi/doctype","#doctype","icon"],                                   
     "Struktur Assets"  =>["docs/intro/configurasi/Assets","#Assets","icon"],                              
     "Assets Condisi"  =>["docs/intro/configurasi/Condisi","#Condisi","icon"],                             
     "Base URL"  =>["docs/intro/configurasi/Base","#Base","icon"],                                         
     "Import Module"  =>["docs/intro/configurasi/Import","#Import","icon"],                                
     "Navbar"  =>["docs/intro/configurasi/Navbar","#Navbar","icon"],                                       
     "Include Path"  =>["docs/intro/configurasi/Include","#Include","icon"],                               
   ],                                                                                                      
   "app_config"    =>[                                                                                     
     "Url Root"  =>["docs/intro/configurasi/root","#root","icon"],                                         
     "Database"  =>["docs/intro/configurasi/database","#database","icon"],                                 
   ],                                                                                                      
   "object_router"    =>[                                                                                  
     "Object"  =>["docs/intro/Router/Object","#Object","icon"],                                            
     "Hashtag"  =>["docs/intro/Router/Hashtag","#Hashtag","icon"],                                         
     "Onclick"  =>["docs/intro/Router/Onclick","#Onclick","icon"],                                         
     "Pages"  =>["docs/intro/Router/Pages","#Pages","icon"],                                               
   ],                                                                                                      
   "db_firebase"    =>[                                                                                    
     "For Each"  =>["docs/DevTools/Firebase=forEach","#Firebase=forEach","icon"],                          
     "Insert"  =>["docs/DevTools/Firebase=Insert","#Firebase=Insert","icon"],                              
     "Update"  =>["docs/DevTools/Firebase=Update","#Firebase=Update","icon"],                              
     "Delete"  =>["docs/DevTools/Firebase=Delete","#Firebase=Delete","icon"],                              
     "Select"  =>["docs/DevTools/Firebase=Select","#Firebase=Select","icon"],                              
     "Push"  =>["docs/DevTools/Firebase=Push","#Firebase=Push","icon"],                                    
     "Limit"  =>["docs/DevTools/Firebase=Limit","#Firebase=Limit","icon"],                                 
   ],                                                                                                      
   "set_firebase"    =>[                                                                                   
     "For Each"  =>["docs/Firebase/Firebase=forEach","#Firebase=forEach","icon"],                          
     "Insert"  =>["docs/Firebase/Firebase=Insert","#Firebase=Insert","icon"],                              
     "Update"  =>["docs/Firebase/Firebase=Update","#Firebase=Update","icon"],                              
     "Delete"  =>["docs/Firebase/Firebase=Delete","#Firebase=Delete","icon"],                              
     "Select"  =>["docs/Firebase/Firebase=Select","#Firebase=Select","icon"],                              
     "Push"  =>["docs/Firebase/Firebase=Push","#Firebase=Push","icon"],                                    
     "Limit"  =>["docs/Firebase/Firebase=Limit","#Firebase=Limit","icon"],                                 
   ],                                                                                                      
   "db_php"    =>[                                                                                         
     "Datetime"  =>["docs/Wolf05/datetime","#datetime","icon"],                                            
     "Text"  =>["docs/Wolf05/text","#text","icon"],                                                        
     "Cookie"  =>["docs/Wolf05/cookie","#cookie","icon"],                                                  
     "Encryption"  =>["docs/Wolf05/encryption","#encryption","icon"],                                      
     "Validation"  =>["docs/Wolf05/validation","#validation","icon"],                                      
     "Images"  =>["docs/Wolf05/resizeimages","#resizeimages","icon"],                                      
   ],                                                                                                      
   "db_office"    =>[                                                                                      
     "Get Token"  =>["docs/ApiReference-office/Token","#Token","icon"],                                    
     "Property"  =>["docs/ApiReference-office/Property","#Property","icon"],                               
     "Pdf"  =>["docs/ApiReference-office/Pdf","#Pdf","icon"],                                              
     "Ppt"  =>["docs/ApiReference-office/Ppt","#Ppt","icon"],                                              
     "Xlsx"  =>["docs/ApiReference-office/Xlsx","#Xlsx","icon"],                                           
     "Docx"  =>["docs/ApiReference-office/Docx","#Docx","icon"],                                           
   ],                                                                                                      
   "db_modules"    =>[                                                                                     
     "Text"  =>["docs/Javascript/Text","#","db_text"],                                                     
     "Date Time"  =>["docs/Javascript/DateTime","#","db_dateTime"],                                        
     "Encode"  =>["docs/Javascript/Decode","#","db_encode"],                                               
     "OnClick"  =>["docs/Javascript/OnClick","#","db_onclick"],                                            
     "Get History"  =>["docs/Javascript/History","#","db_onclick"],                                        
     "User Agent"  =>["docs/Javascript/userAgent","#","db_onclick"],                                       
     "Location"  =>["docs/Javascript/Location","#","db_onclick"],                                          
     "Shortcut"  =>["docs/Javascript/Shortcut","#","db_onclick"],                                          
     "SetLink"  =>["docs/Javascript/SetLink","#","db_onclick"],                                            
   ],                                                                                                      
   "db_dateTime"    =>[                                                                                    
     "Date Hari"  =>["docs/Javascript/DateTime=setDateTime=hari","#DateTime=setDateTime=hari","icon"],     
     "Date Bulan"  =>["docs/Javascript/DateTime=setDateTime=bulan","#DateTime=setDateTime=bulan","icon"],  
     "Date Tahun"  =>["docs/Javascript/DateTime=setDateTime=tahun","#DateTime=setDateTime=tahun","icon"],  
     "Date Jam"  =>["docs/Javascript/DateTime=setDateTime=jam","#DateTime=setDateTime=jam","icon"],        
     "Date EN"  =>["docs/Javascript/DateTime=setDateTime=EN","#DateTime=setDateTime=EN","icon"],           
     "Date DIN"  =>["docs/Javascript/DateTime=setDateTime=DIN","#DateTime=setDateTime=DIN","icon"],        
     "Date IN"  =>["docs/Javascript/DateTime=setDateTime=IN","#DateTime=setDateTime=IN","icon"],           
     "Date IND"  =>["docs/Javascript/DateTime=setDateTime=IND","#DateTime=setDateTime=IND","icon"],        
     "Date Day"  =>["docs/Javascript/DateTime=setDateTime=Day","#DateTime=setDateTime=Day","icon"],        
     "Date Month"  =>["docs/Javascript/DateTime=setDateTime=Month","#DateTime=setDateTime=Month","icon"],  
     "Date Year"  =>["docs/Javascript/DateTime=setDateTime=Year","#DateTime=setDateTime=Year","icon"],     
     "Date Bln"  =>["docs/Javascript/DateTime=setDateTime=Bln","#DateTime=setDateTime=Bln","icon"],        
     "Date Time"  =>["docs/Javascript/DateTime=setDateTime=time","#DateTime=setDateTime=time","icon"],     
     "Date Time dmy"  =>["docs/Javascript/DateTime=setDateTime=dmy","#DateTime=setDateTime=dmy","icon"],   
     "Time v"  =>["docs/Javascript/DateTime=setDateTime=v","#DateTime=setDateTime=v","icon"],              
     "Time time"  =>["docs/Javascript/DateTime=setDateTime=timex","#DateTime=setDateTime=timex","icon"],   
     "Time Day"  =>["docs/Javascript/DateTime=setDateTime=day","#DateTime=setDateTime=day","icon"],        
     "Time Month"  =>["docs/Javascript/DateTime=setDateTime=month","#DateTime=setDateTime=month","icon"],  
     "Time Year"  =>["docs/Javascript/DateTime=setDateTime=year","#DateTime=setDateTime=year","icon"],     
   ],                                                                                                      
   "db_encode"    =>[                                                                                      
     "Set Decode"  =>["docs/Javascript/Decode=setDecode","#Decode=setDecode","icon"],                      
     "Set Token"  =>["docs/Javascript/Decode=setToken","#Decode=setToken","icon"],                         
     "Get Token"  =>["docs/Javascript/Decode=getToken","#Decode=getToken","icon"],                         
   ],                                                                                                      
   "db_onclick"    =>[                                                                                     
     "Insert"  =>["docs/Javascript/OnClick=insert","#OnClick=insert","icon"],                              
     "Update"  =>["docs/Javascript/OnClick=update","#OnClick=update","icon"],                              
     "Stack"  =>["docs/Javascript/OnClick=stack","#OnClick=stack","icon"],                                 
     "Delete Permananet"  =>["docs/Javascript/OnClick=permananet","#OnClick=permananet","icon"],           
     "Delete Temporarily"  =>["docs/Javascript/OnClick=temporarily","#OnClick=temporarily","icon"],        
     "Upload Images"  =>["docs/Javascript/OnClick=images","#OnClick=images","icon"],                       
     "Upload Document"  =>["docs/Javascript/OnClick=documents","#OnClick=documents","icon"],               
     "Import Excel"  =>["docs/Javascript/OnClick=import","#OnClick=import","icon"],                        
     "Modal"  =>["docs/Javascript/OnClick=modals","#OnClick=modals","icon"],                               
     "Plugin"  =>["docs/Javascript/OnClick=plugis","#OnClick=plugis","icon"],                              
     "Target"  =>["docs/Javascript/OnClick=targets","#OnClick=targets","icon"],                            
     "Dom Pdf"  =>["docs/Javascript/OnClick=dopdf","#OnClick=dopdf","icon"],                               
     "Prind Raw"  =>["docs/Javascript/OnClick=prindraw","#OnClick=prindraw","icon"],                       
     "Route"  =>["docs/Javascript/OnClick=routes","#OnClick=routes","icon"],                               
     "Dialog"  =>["docs/Javascript/OnClick=dialogs","#OnClick=dialogs","icon"],                            
     "Link Route"  =>["docs/Javascript/OnClick=lroute","#OnClick=lroute","icon"],                          
     "Link Sign"  =>["docs/Javascript/OnClick=lsign","#OnClick=lsign","icon"],                             
   ],                                                                                                      
   "db_text"    =>[                                                                                        
     "Romawi"  =>["docs/Javascript/Text=romawi","#Text=romawi","icon"],                                    
     "Readmore"  =>["docs/Javascript/Text=readmore","#Text=readmore","icon"],                              
     "Substr"  =>["docs/Javascript/Text=substr","#Text=substr","icon"],                                    
     "Split"  =>["docs/Javascript/Text=setSplit","#Text=setSplit","icon"],                                 
     "Replace"  =>["docs/Javascript/Text=replace","#Text=replace","icon"],                                 
     "Rupiah"  =>["docs/Javascript/Text=rupiah","#Text=rupiah","icon"],                                    
     "Terbilang"  =>["docs/Javascript/Text=terbilang","#Text=terbilang","icon"],                           
     "Explode"  =>["docs/Javascript/Text=explode","#Text=explode","icon"],                                 
   ],                                                                                                      
  ];                                                                                                       
