<?php 
use app\tatiye;
echo''.PHP_EOL;
echo'/**'.PHP_EOL;
echo' * TatiyeNet - PHP Helpers for Develover wolf05'.PHP_EOL;
echo' *'.PHP_EOL;
echo' * (The MIT License)'.PHP_EOL;
echo' *'.PHP_EOL;
echo' * Copyright (c) 2020 wolf05 <info@tatiye.net / https://www.facebook.com/tatiyeNet/>.'.PHP_EOL;
echo' *'.PHP_EOL;
echo' * Permission is hereby granted, free of charge, to any person obtaining a copy'.PHP_EOL;
echo' * of this software and associated documentation files (the "Software"), to deal'.PHP_EOL;
echo' * in the Software without restriction, including without limitation the rights'.PHP_EOL;
echo' * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell'.PHP_EOL;
echo' * copies of the Software, and to permit persons to whom the Software is'.PHP_EOL;
echo' * furnished to do so, subject to the following conditions:'.PHP_EOL;
echo' *'.PHP_EOL;
echo' * The above copyright notice and this permission notice shall be included in'.PHP_EOL;
echo' * all copies or substantial portions of the Software.'.PHP_EOL;
echo' *'.PHP_EOL;
echo' * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR'.PHP_EOL;
echo' * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,'.PHP_EOL;
echo' * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE'.PHP_EOL;
echo' * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER'.PHP_EOL;
echo' * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,'.PHP_EOL;
echo' * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN'.PHP_EOL;
echo' * THE SOFTWARE.'.PHP_EOL;
echo' */'.PHP_EOL;
echo'namespace app\config;'.PHP_EOL;
echo'/**'.PHP_EOL;
echo' * on how to display  component.'.PHP_EOL;
echo' *'.PHP_EOL;
echo' * See {@link https://tatiye.net/} for more information.'.PHP_EOL;
echo' */'.PHP_EOL;
echo'class database  {'.PHP_EOL;
echo' /*'.PHP_EOL;
echo' |--------------------------------------------------------------------------'.PHP_EOL;
echo' | Initializes database '.PHP_EOL;
echo' |--------------------------------------------------------------------------'.PHP_EOL;
echo' | Develover Tatiye.Net 2024'.PHP_EOL;
echo' | @Date '.tatiye::dt('DTIE').' '.PHP_EOL;
echo' */'.PHP_EOL;
echo' public static function db(){'.PHP_EOL;
echo'      return  array('.PHP_EOL;
echo'        "driver"   =>"mysqli",'.PHP_EOL;
echo'        "port"     =>"80",'.PHP_EOL;
echo'        "host"     =>"'.$_POST['host'].'",'.PHP_EOL;
echo'        "username" =>"'.$_POST['username'].'",'.PHP_EOL;
echo'        "password" =>"'.$_POST['password'].'",'.PHP_EOL;
echo'        "database" =>"'.$_POST['database'].'",'.PHP_EOL;
echo'      );'.PHP_EOL;    
echo' }'.PHP_EOL;
echo' /* and class database */'.PHP_EOL;
echo' /*'.PHP_EOL;
echo' |--------------------------------------------------------------------------'.PHP_EOL;
echo' | Akses Database firebase '.PHP_EOL;
echo' |--------------------------------------------------------------------------'.PHP_EOL;
echo' | Develover Tatiye.Net 2024'.PHP_EOL;
echo' | @Date '.tatiye::dt('DTIE').' '.PHP_EOL;
echo' */'.PHP_EOL;
echo' public static function firebase(){'.PHP_EOL;
echo'  return  array('.PHP_EOL;
echo'      "status"                =>true,'.PHP_EOL;
echo'      "database"              =>['.PHP_EOL;
echo'          "apiKey"            =>false,'.PHP_EOL;
echo'          "authDomain"        =>false,'.PHP_EOL;
echo'          "databaseURL"       =>false,'.PHP_EOL;
echo'          "projectId"         =>false,'.PHP_EOL;
echo'          "storageBucket"     =>false,'.PHP_EOL;
echo'          "messagingSenderId" =>false,'.PHP_EOL;
echo'          "appId"             =>false,'.PHP_EOL;
echo'      ],'.PHP_EOL;
echo'    );'.PHP_EOL;
echo' }'.PHP_EOL;
echo' /*'.PHP_EOL;
echo' |--------------------------------------------------------------------------'.PHP_EOL;
echo' | Akses Tabel Api  tabelApi '.PHP_EOL;
echo' |--------------------------------------------------------------------------'.PHP_EOL;
echo' | Develover Tatiye.Net 2024'.PHP_EOL;
echo' | @Date '.tatiye::dt('DTIE').' '.PHP_EOL;
echo' */'.PHP_EOL;
echo' public static function tabelApi(){'.PHP_EOL;
echo'     return array('.PHP_EOL;
echo'        "demo" =>true'.PHP_EOL;
echo'   );'.PHP_EOL;
echo' }'.PHP_EOL;
echo' /* and class tabelApi */'.PHP_EOL;
echo'}'.PHP_EOL;

